Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,6 +26,11 @@ jobs:
       run: |
         set -e
         npx eslint 'script.js' --max-warnings 0 | tee lint-output.txt
+        LINT_EXIT_CODE=$?
+        if [ "$LINT_EXIT_CODE" -ne 0 ]; then
+          echo "Linter failed with exit code $LINT_EXIT_CODE"
+          exit 1
+        fi
       
     - name: Send fail message to Telegram 
       if: ${{ failure() }}
